#!/bin/bash

_check_agent_alive() {
    if ps -p $SSH_AGENT_PID > /dev/null; then
        if [[ $(ps -p $SSH_AGENT_PID -o cmd=) = ssh-agent ]]; then
            ssh-add -l > /dev/null 2>&1
            case $? in
                2)
                    kill $SSH_AGENT_PID
                    ;;
                0|1)
                    return 0
                    ;;
                *)
                    : # wft no handled
                    ;;
            esac
        fi
    fi
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
    return 1
}
            
_get_agent_started() {
    local _disk_keyring

    _disk_keyring=$HOME/.keyring-${HOSTNAME:-$(hostname)}
    if [[ -z $SSH_AUTH_SOCK ]]; then
        if [[ -r $_disk_keyring ]]; then
            # shellcheck disable=SC1090
            source $_disk_keyring
        fi
    fi
    if [[ -n $SSH_AUTH_SOCK ]]; then
        if _check_agent_alive; then
            return 0
        fi
    fi
    eval $(ssh-agent | tee <(grep -v ^echo > $_disk_keyring))
    sleep 1
    return 0
}


_init_keyring() {
    ssh-add -l >/dev/null 2>&1
    case $? in
        1)
            ssh-add
            ;;
        *)
            return $?
            ;;
    esac
}


_get_agent_started
_init_keyring
