#!/bin/bash

_check_agent_alive() {

    local cmdline
    if [[ -d /proc/${SSH_AGENT_PID} ]]; then
        read -r cmdline < /proc/${SSH_AGENT_PID}/cmdline
        if [[ ${cmdline} =~ ssh-agent ]]; then
            ssh-add -l &> /dev/null
            case $? in
                2)
                    kill "$SSH_AGENT_PID"
                    ;;
                0|1)
                    return 0
                    ;;
                *)
                    : # wft no handled
                    ;;
            esac
        fi
    fi
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
    return 1
}
            
_get_agent_started() {
    local _disk_keyring

    _disk_keyring=$HOME/.keyring-${HOSTNAME:-$(hostname)}
    if [[ -z $SSH_AUTH_SOCK || -z $SSH_AGENT_PID ]]; then
        # shellcheck disable=SC1090
        [[ -r $_disk_keyring ]] && source "$_disk_keyring"
    fi
    if [[ -n $SSH_AUTH_SOCK && -n $SSH_AGENT_PID ]]; then
        if _check_agent_alive; then
            return 0
        fi
    fi
    # shellcheck disable=SC2046 disable=SC2086
    eval $(ssh-agent | tee >(grep -v ^echo > $_disk_keyring))
    sleep 1
    return 0
}


_init_keyring() {
    ssh-add -l >/dev/null 2>&1
    case $? in
        1)
            ssh-add
            ;;
        *)
            return $?
            ;;
    esac
}


_get_agent_started
_init_keyring
