#! /bin/bash
#
# Bash functions for tmux

tmux_if_started()   # window name, command
{
    [[ -n "$TMUX" ]] && { 
	local target
	target=$(tmux new-window -P -n "$1" "$2")
	tmux set-window-option -t "${target//.*/}" remain-on-exit on > /dev/null 2>&1
	return 0
    }
    $2
}

_tmux_temp_window_name() {  # name command
    local LC_ALL=C
    local _nwn=$1
    shift
    [[ -n $TMUX ]] && {
        tmux rename-window "${_nwn}"
    }
    command "$@"
    [[ -n $TMUX ]] && {
        tmux set-window-option automatic-rename on > /dev/null
    }
}

ssh()
{
    _tmux_temp_window_name "@${!#}" ssh "$@"
}

sssh()
{
    [ -z "$1" ] && { echo "Huh?"; echo "Perhaps you forgot where you were ssh-ing to?"; return 1; }
    tmux_if_started "@${1//.*/}" "ssh $1"
}

command2fileshell_version()
{
# convert a command line to a filename, i.e. remove non-shell filename characters (or escape as necessary)
    local fn
    shopt -s extglob
    fn=${*:-${SHELL}}
    # can't get the incantation right (yet)
    echo "${fn//!(A-Za-z0-9.-)/_}"
}
command2file() {
    # shellcheck disable=SC2001
    # can't get shell do it (yet) see above
    echo "${@:-${SHELL}}" | sed -e 's/[^A-Za-z0-9._-]/_/g'
}


# for some dm (or critical stuff) I want to log
dm()
{
    local LOGDIR
    local target
    local name
    LOGDIR=$HOME/dmlog/$(date +%Y%m%d)
    [[ -d $LOGDIR ]] || mkdir -p "$LOGDIR"
    LOGFILE=$(mktemp -p "$LOGDIR" "$(date +%H%M%S)-XXXXXX-$(command2file "$*").log")
    {
	echo "$(date): Starting '${*:-$SHELL}' on $(hostname)"
	uname -a
	echo "------------------------------------------------------------------------------" 
    } > "$LOGFILE"

    name=dm:${1:-$SHELL}
    [ "$1" = "ssh" ] && name="dm@${2}"
    # remove some common cruft
    name=${name/secserv-/}
    name=${name/.ficc.gs.com/}
    target=$(tmux new-window -P -n "${name}" "$*")
    tmux set-window-option -t "${target//.*/}" remain-on-exit on > /dev/null 2>&1
    tmux pipe-pane -o -t "${target}" "exec cat >> $LOGFILE"
}

ww() {
    tmux split-window -d -l 80 -h\; split-window -d -l 20\;  rename-window "${@:-work}"
    tmux_prompt
}
