# Pane content (inactive slightly dimmer than active)
set -g window-style        'bg=#eee8d5,fg=#93a1a1'    # base2 bg, base1 fg
set -g window-active-style 'bg=#fdf6e3,fg=#657b83'    # base3 bg, base00 fg
set -g pane-border-style        'fg=#93a1a1'          # base1 — muted
set -g pane-active-border-style 'fg=#268bd2,bold'     # solarized blue

set-option -g status-style bg=colour222,fg=colour95,bright #dark blue/dark green

set-window-option -g window-status-style bg=default,fg=colour207,dim #blue
set-window-option -g window-status-current-style bg=default,fg=colour201,bright

set-option -g message-style bg=colour229,fg=colour166

# vim: set filetype=tmux sts=2 sw=2:
