[tools]
argocd = "3.1"
aws = "latest"
helm = "3.18"
jq = "latest"
kubectl = "1.31"
kubectx = "latest"
kubens = "latest"
kustomize = "5.4"
saml2aws = "latest"
usage = "latest"
uv = "latest"
vault = "1.15"
yq = "latest"
