[tools]
argocd = "3.1"
aws = "latest"
gh = "latest"
go-jira = "latest"
grpcurl = "latest"
helm = "3.18"
jq = "latest"
k9s = "latest"
kubectl = "1.31"
kubectx = "latest"
kubens = "latest"
kustomize = "5.4"
"aqua:neovim/neovim" = "latest"
pre-commit = "latest"
ripgrep = "latest"
saml2aws = "latest"
shellcheck = "latest"
"asdf:mise-plugins/mise-tmux" = "latest"
usage = "latest"
uv = "latest"
vault = "1.15"
vim = "latest"
yq = "latest"
"github:ankitpokhrel/jira-cli" = "latest"
"github:k8sgpt-ai/k8sgpt" = "latest"
node = "latest"

[settings]
trusted_config_paths = ["~/src"]
